#!/usr/bin/env bash

set -eo pipefail

echo >&2 "restarting deployments..."
kubectl --namespace $NAMESPACE get deployments |\
  tail +2          |\
  cut -d ' '  -f 1 |\
  xargs -I % sh -c "kubectl --namespace ${NAMESPACE} rollout restart deployment %"

exit_code="$?"
ns_deployments=$(kubectl get -n $NAMESPACE deployments -o json)
payload=`jq --null-input --arg exitCode "$exit_code" --argjson deploymentsJson "$ns_deployments" '{"exit_code": $exitCode, "deployments": $deploymentsJson}'`
echo $payload >> $NUON_ACTIONS_OUTPUT_FILEPATH
