#!/usr/bin/env sh

set -e
set -o pipefail
set -u


echo "running healthcheck"
echo " endpoint: $ENDPOINT"
echo "  expects: $EXPECTED_STATUS_CODE"


# set the method
method="${METHOD:-GET}"
# validate the method is allowed
case $method in 'GET'|'HEAD')
    echo "   method: $method";;
    *)
    echo "   invalid method: $method"; exit 2;;
esac


# excute the request
response=`curl --silent -o - -I -X $method $ENDPOINT`

# get the status code
status_code=`echo $response | head -n 1 | cut -d ' ' -f 2`
echo "status_code=$status_code"


if [ "$status_code" == "$EXPECTED_STATUS_CODE" ];
  then
    success="true"
    indicator="🟢"
  else
    success="false"
    indicator="🔴"
fi
# save the status code as an output
echo '{"status_code": "'$status_code'", "success": "'$success'", "indicator": "'$indicator'"}' >> $NUON_ACTIONS_OUTPUT_FILEPATH
